k8gb:
  clusterGeoTag: "us"
  extGslbClustersGeoTags: "eu"

extdns:
  enabled: true
  txtPrefix: "k8gb-us-"
  txtOwnerId: "k8gb-us"
  provider:
    name: aws
  env:
  - name: AWS_DEFAULT_REGION
    value: "eu-central-1"
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: .aws/credentials
  extraVolumes:
  - name: aws-credentials
    secret:
      secretName: credentials
  extraVolumeMounts:
  - name: aws-credentials
    mountPath: /.aws
    readOnly: true
