package refresolver

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	"github.com/k8gb-io/k8gb/controllers/providers/dns"
	netv1 "k8s.io/api/networking/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type GslbReferenceResolver interface {
	// ResolveGslbReferences fills Gslb's LoadBalancer and Server values based on the Ingress configuration
	ResolveGslbReferences(gslb *k8gbv1beta1.Gslb, k8sClient client.Client, dnsProvider dns.Provider) error
	// GetIngress retrieves a Kubernetes Ingress resource for a GSLB resource
	GetIngress(gslb *k8gbv1beta1.Gslb, k8sClient client.Client) (*netv1.Ingress, error)
	// GetServers retrieves Gslb's Server configuration based on a Kubernetes Ingress configuration
	GetServers(ingress *netv1.Ingress, k8sClient client.Client) ([]*k8gbv1beta1.Server, error)
}
