package refresolver

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"fmt"
	"reflect"
	"strings"

	k8gbv1beta1 "github.com/k8gb-io/k8gb/api/v1beta1"
	"github.com/k8gb-io/k8gb/controllers/internal/utils"
	istio "istio.io/client-go/pkg/apis/networking/v1beta1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type VirtualServiceReferenceResolver struct {
	virtualService *istio.VirtualService
	gateway        *istio.Gateway
}

func NewVirtualServiceReferenceResolver(gslb *k8gbv1beta1.Gslb, k8sClient client.Client) (*VirtualServiceReferenceResolver, error) {
	virtualServiceList, err := getGslbVirtualServiceRef(gslb, k8sClient)
	if err != nil {
		return nil, err
	}

	if len(virtualServiceList) != 1 {
		return nil, fmt.Errorf("exactly one VirtualService resource expected but %d were found", len(virtualServiceList))
	}
	virtualService := virtualServiceList[0]

	gateway, err := getGateway(virtualService, k8sClient)
	if err != nil {
		return nil, err
	}

	return &VirtualServiceReferenceResolver{
		virtualService: virtualService,
		gateway:        gateway,
	}, nil
}

// getGslbVirtualServiceRef resolves a gateway-api HTTP Route resource referenced by the Gslb spec
func getGslbVirtualServiceRef(gslb *k8gbv1beta1.Gslb, k8sClient client.Client) ([]*istio.VirtualService, error) {
	virtualServiceList := &istio.VirtualServiceList{}
	if reflect.DeepEqual(gslb.Spec.ResourceRef.VirtualService, metav1.LabelSelector{}) {
		log.Warn().
			Str("gslb", gslb.Name).
			Msg("No configuration for referenced VirtualService resource")
		return virtualServiceList.Items, nil
	}

	selector, err := metav1.LabelSelectorAsSelector(&gslb.Spec.ResourceRef.VirtualService)
	if err != nil {
		return nil, err
	}
	opts := &client.ListOptions{
		LabelSelector: selector,
	}

	err = k8sClient.List(context.TODO(), virtualServiceList, opts)
	if err != nil {
		if errors.IsNotFound(err) {
			log.Info().
				Str("gslb", gslb.Name).
				Msg("Can't find referenced VirtualService resource")
		}
		return nil, err
	}

	return virtualServiceList.Items, err
}

// getGateway
func getGateway(virtualService *istio.VirtualService, k8sClient client.Client) (*istio.Gateway, error) {
	if len(virtualService.Spec.Gateways) != 1 {
		return nil, fmt.Errorf("exactly one Gateway on the VirtualService expected but %d were found", len(virtualService.Spec.Gateways))
	}
	gatewayRef := strings.Split(virtualService.Spec.Gateways[0], "/")
	gatewayNamespace := gatewayRef[0]
	gatewayName := gatewayRef[1]

	gateway := &istio.Gateway{}
	err := k8sClient.Get(context.TODO(), types.NamespacedName{
		Namespace: gatewayNamespace,
		Name:      gatewayName,
	}, gateway)
	if err != nil {
		if errors.IsNotFound(err) {
			log.Info().
				Str("gatewayNamespace", string(gatewayNamespace)).
				Str("gatewayName", string(gatewayName)).
				Msg("Can't find Gateway resource referenced by VirtualService")
		}
		return nil, err
	}

	return gateway, nil
}

// GetServers retrieves the server configuration of the GSLB from a Kubernetes ingress resource
func (vsrr *VirtualServiceReferenceResolver) GetServers() ([]*k8gbv1beta1.Server, error) {
	hosts := vsrr.virtualService.Spec.Hosts
	if len(hosts) < 1 {
		return nil, fmt.Errorf("can't find hosts in VirtualService %s", vsrr.virtualService.Name)
	}

	servers := []*k8gbv1beta1.Server{}
	for _, host := range hosts {
		server := &k8gbv1beta1.Server{
			Host:     host,
			Services: []*k8gbv1beta1.NamespacedName{},
		}
		for _, http := range vsrr.virtualService.Spec.Http {
			for _, route := range http.Route {
				server.Services = append(server.Services, &k8gbv1beta1.NamespacedName{
					Name:      route.Destination.Host,
					Namespace: vsrr.virtualService.Namespace,
				})
			}
		}
		servers = append(servers, server)

	}

	return servers, nil
}

// GetGslbExposedIPs retrieves the load balancer IP address of the GSLB
func (vsrr *VirtualServiceReferenceResolver) GetGslbExposedIPs(gslb *k8gbv1beta1.Gslb, k8sClient client.Client, edgeDNSServers utils.DNSList) ([]string, error) {
	gatewayServiceList := &corev1.ServiceList{}
	opts := &client.ListOptions{
		LabelSelector: labels.SelectorFromSet(vsrr.gateway.Spec.Selector),
	}

	err := k8sClient.List(context.TODO(), gatewayServiceList, opts)
	if err != nil {
		if errors.IsNotFound(err) {
			log.Info().
				Str("gslb", gslb.Name).
				Str("gateway", vsrr.gateway.Name).
				Str("virtualService", vsrr.virtualService.Name).
				Msg("Can't find any service with the gateway's selector")
		}
		return nil, err
	}

	if len(gatewayServiceList.Items) != 1 {
		return nil, fmt.Errorf("exactly one Service resource expected but %d were found", len(gatewayServiceList.Items))
	}

	gatewayService := &gatewayServiceList.Items[0]

	var gslbIngressIPs []string
	for _, ip := range gatewayService.Status.LoadBalancer.Ingress {
		if len(ip.IP) > 0 {
			gslbIngressIPs = append(gslbIngressIPs, ip.IP)
		}
		if len(ip.Hostname) > 0 {
			IPs, err := utils.Dig(ip.Hostname, edgeDNSServers...)
			if err != nil {
				log.Warn().Err(err).Msg("Dig error")
				return nil, err
			}
			gslbIngressIPs = append(gslbIngressIPs, IPs...)
		}
	}

	return gslbIngressIPs, nil
}
