package utils

/*
Copyright 2022 The k8gb Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"fmt"
	"net"
	"sort"
	"strings"
)

// ParseIPAddresses parse a comma separated string of ip addresses into a list of net.IP
func ParseIPAddresses(IPsStr string) ([]net.IP, error) {
	IPs := make([]net.IP, 0)
	for _, ipStr := range strings.Split(IPsStr, ",") {
		ipAddr := net.ParseIP(ipStr)
		if ipAddr == nil {
			return nil, fmt.Errorf("invalid IP address: %s", ipStr)
		}
		IPs = append(IPs, ipAddr)
	}

	return IPs, nil
}

func IPSliceToStringSlice(IPs []net.IP) []string {
	strs := make([]string, len(IPs))
	for i, ip := range IPs {
		strs[i] = ip.String()
	}
	return strs
}

// lexicographically sorts a list of IP addresses
// the actual order is not important, it is only important that it is constant
func sortIPAddresses(ips []net.IP) {
	sort.Slice(ips, func(i, j int) bool {
		return ips[i].String() < ips[j].String()
	})
}
