name: Github Pages

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - 'docs/**'
permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0
      - name: Copy new docs to gh-pages
        run: |
          git checkout gh-pages
          git checkout ${GITHUB_REF##*/} ADOPTERS.md
          git checkout ${GITHUB_REF##*/} README.md
          git checkout ${GITHUB_REF##*/} CONTRIBUTING.md
          git checkout ${GITHUB_REF##*/} CHANGELOG.md
          git checkout ${GITHUB_REF##*/} docs
      - name: Push to gh-pages
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Documentation sync from master"
          branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
