name: KubeLinter

on:
  push:
    paths:
      - 'chart/k8gb/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'chart/k8gb/**'
permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Create ../results directory for sarif files
        shell: bash
        run: mkdir -p ../results

      - name: Scan k8gb chart
        id: kube-lint-repo
        uses: stackrox/kube-linter-action@ca0d55b925470deb5b04b556e6c4276ea94d03c3 # v1.0.4
        with:
          directory: chart/k8gb
          version: 0.2.5
          format: sarif
          output-file: ../results/kube-linter.sarif

      - name: Upload sarif output to GitHub
        uses: github/codeql-action/upload-sarif@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
        continue-on-error: true
